### ISSUE TITLE
[Question] How are the "Most Requested" terms selected?

### ISSUE THREAD

**Issue by cedricium** [maximforever/dictionary#12]
Hey @maximforever, first off let me just say that Hackterms is an awesome site! 🎉 I'm currently developing my first fullstack webapp and I've been able to learn a lot from what you've done here.

Question for you is: how are the "Most Requested" terms selected / chosen? Looking at the current list, the top one (presumably) is "marmosetjs" which AFAIK isn't really a thing. Whereas the "Trending" section seems to have good data, the "Most Requested" sections seems like a testbed for exploits so I'm wondering why those would be the "Most Requested" instead of getting filtered out by regular users use of normal terms?

**Reference Image:**
![screen shot 2018-02-25 at 10 09 51 am](https://user-images.githubusercontent.com/16343560/36644885-6b5a93f6-1a15-11e8-9761-58475b53e643.png)

**Comment by maximforever** [comment]
Hey, thanks so much! Great catch, and thanks for asking. Hackterms is not my first full-stack app, but definitely by far my biggest - so I'm learning right alongside ya :)

Happy to explain how `most requested` terms work. I spent a while thinking about this problem, and didn't find a perfect solution - but settled on what I think is a pretty good one. `Trending` terms are easy - I just list the most searched terms. The problem with requested terms - that is, terms without definitions - is that people often don't search the whole term. So, let's say "angularjs" doesn't have a definition. The thing is, because I am searching instantly on every letter, someone might type `angu`, and stop - and then we just have `angu` as a search; and maybe other searches that go `angul` and `ang` and `angula`. The tough part of this problem is that we're trying to predict/anticipate what people are trying to say. So, for every incoming search with no definitions, I log the term, and then check _if it's a subterm of other requests_. So, we end up with longer and longer words - as soon as someone searches `angularjs`, `ang` and `angul` will both count towards the full term.

It's not a perfect solution, and leaves open the possibility of typos (as in `emacsh` above) and trolling (yesterday, we were getting rickrolled :)
![screen shot 2018-02-25 at 1 53 22 am](https://user-images.githubusercontent.com/8518720/36645715-026108fa-1a3b-11e8-8dda-2c38bf685f5c.png)

So, realistically, I look at the list frequently and tweak it to get rid of gibberish and add useful terms - and they're often getting defined!

**Comment by cedricium** [comment]
Thanks for the answer! I can indeed see how trying to anticipate searches would be difficult - this poses an interesting engineering problem which requires a well thought-out solution.

**Comment by maximforever** [comment]
Thanks, man! If you're curious about this kind of stuff or want to help think/talk through ideas, feel free to join us on the [Hackterms Slack](https://join.slack.com/t/hackterms/shared_invite/enQtMzE0NTEwMTI1MDYxLTcyNTY5YWY0ODI0YmM3Yzk5YzkyMTVhMmUzOGNhYzkyNDQzODU0ZTBhNmFiNzAwNzI0Nzc2ODE4NTQ1OTViMTA)
